# Generated by Django 3.2.12 on 2022-02-06 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "status",
                    models.CharField(
                        choices=[("ENABLED", "ENABLED"), ("REMOVED", "REMOVED")],
                        default="ENABLED",
                        max_length=7,
                    ),
                ),
                (
                    "campaign_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("structure_value", models.CharField(max_length=50)),
            ],
            options={
                "ordering": ["structure_value"],
            },
        ),
        migrations.CreateModel(
            name="AdGroup",
            fields=[
                (
                    "status",
                    models.CharField(
                        choices=[("ENABLED", "ENABLED"), ("REMOVED", "REMOVED")],
                        default="ENABLED",
                        max_length=7,
                    ),
                ),
                (
                    "ad_group_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("alias", models.CharField(max_length=255)),
                (
                    "campaign_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ad_campaign.campaign",
                    ),
                ),
            ],
            options={
                "ordering": ["alias"],
            },
        ),
        migrations.CreateModel(
            name="SearchTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("clicks", models.IntegerField(default=0)),
                ("cost", models.FloatField()),
                ("conversion_value", models.FloatField(default=0)),
                ("conversions", models.IntegerField(default=0)),
                ("search_term", models.CharField(max_length=255)),
                ("roas", models.FloatField(db_index=True, default=0)),
                (
                    "ad_group_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_terms",
                        to="ad_campaign.adgroup",
                    ),
                ),
                (
                    "campaign_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_terms",
                        to="ad_campaign.campaign",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {
                    ("date", "ad_group_id", "campaign_id", "search_term")
                },
            },
        ),
    ]
