# Generated by Django 3.2.11 on 2022-01-25 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaigns",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ENABLED", "ENABLED"), ("REMOVED", "REMOVED")],
                        default="ENABLED",
                        max_length=7,
                    ),
                ),
                ("campaign_id", models.BigIntegerField(null=True)),
                ("structure_value", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SearchTerms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("ad_group_id", models.BigIntegerField()),
                ("clicks", models.IntegerField(default=0)),
                ("cost", models.FloatField()),
                ("conversion_value", models.IntegerField(default=0)),
                ("conversions", models.IntegerField(default=0)),
                ("search_term", models.CharField(max_length=255)),
                (
                    "campaign_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ad_campaign.campaigns",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdGroups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ENABLED", "ENABLED"), ("REMOVED", "REMOVED")],
                        default="ENABLED",
                        max_length=7,
                    ),
                ),
                ("ad_group_id", models.BigIntegerField()),
                ("alias", models.CharField(max_length=255)),
                (
                    "campaign_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ad_campaign.campaigns",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
